[LOOK OVER CODE BEFORE YOU MERGE] Start of options menu and full options integration.
xhayper/dr-k-bot pull request #2
Opened 2022-04-26 22:04 UTC by TrixyMixy

Nothing is really integrated with the options menu yet, just want to let you look over this so you can choose what you like and don't like before I go through the effort of integrating it.

It's a little bit of a mess since I did it on mobile, but it should still be functional.

2022-04-26 22:12 UTC, TrixyMixy commented
Completely forgot I wanted to also add options to change the home channel and role selection channel, I'm stupid, I'll get back to you with those after this pull gets taken care of.

2022-04-27 00:29 UTC, xhayper commented
a lot of hardcoded is there for a reason, as shellac want stuff to be loke that

2022-04-27 00:53 UTC, xhayper commented
i need to talk to shellac about this

2022-04-27 00:54 UTC, TrixyMixy commented
Not quite sure why you would want stuff to be hard coded and unchangeable even by head mods, seems inconvenient at best.

2022-04-27 00:54 UTC, xhayper commented
also, dr k DOES NOT have delete perms

2022-04-27 01:02 UTC, TrixyMixy commented
WH- Ok.
That's rather inconvenient for filters, going to have to put those on the back burner.

2022-04-27 15:55 UTC, xhayper requested changes

2022-04-27 15:55 UTC, Khaomi commented on src/event/messageCreate.ts
> +var savedMessages = { // Only a list of general-1 messages for now.
Consider using `const` instead of `var`,
Since we are using this in general right now, the ideal setup could be `Collection<Snowflake, number>`, where the `Snowflake` is userId and `number` is the amount of post, resetting in 1 minutes using `setTimeout`

2022-04-27 15:55 UTC, Khaomi commented on src/event/messageCreate.ts
> +        if (message.attachments.size > 0) { // Doesn't differentiate between attatchements, might have to fix that later.
Consider implementing the feature i asked in previous review, as it's saving memory and stuff, and easier to understand

2022-04-27 15:55 UTC, Khaomi commented on src/config.ts
> +  misc: {
Misc shouldn't be used now, as everything is hardcoded because of shellac

2022-04-27 15:55 UTC, Khaomi commented on src/command/optionsCommand.ts
> +export default {
This command is not used, all of the value is hard-coded because of shellac

2022-04-27 16:05 UTC, TrixyMixy commented
Just saw requests, will get on that.

2022-04-27 16:08 UTC, TrixyMixy commented on src/command/optionsCommand.ts
> +export default {
Alright, even though I don't agree with that approach, I'll go along with it and leave customization out of the merge.

2022-04-27 16:09 UTC, TrixyMixy commented on src/config.ts
> +  misc: {
Media Timer and media limit is still pulled from there, and I'd prefer it to stay that way.

2022-04-27 16:23 UTC, TrixyMixy commented on src/event/messageCreate.ts
> +var savedMessages = { // Only a list of general-1 messages for now.
I just added in general 2, dunno how that'll work with the collection feature. 
Will change to const, var is just a force of habbit ha.

2022-04-27 16:47 UTC, TrixyMixy reviewed
Cool.

2022-04-27 16:51 UTC, TrixyMixy commented
Do you want me to make the current system into a media limit that keeps track with each person? Seems like it would be a lot more intensive but doable.

2022-04-27 17:28 UTC, TrixyMixy commented
Something like this work?

2022-04-28 11:28 UTC, merged